plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.1'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '6.25.0'
	id 'org.barfuin.gradle.jacocolog' version '3.1.0'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'Demo project for Spring Boot'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

ext {
    // Minimal Coverage
    minimumCoveragePerFile = 0.5
    filesExcludedFromCoverage = [
            "**/*MarketApplication.*",
            "**/config/*Configuration.*",
            "**/exception/*",
            "**/dto/*"
    ]
}

repositories {
	mavenCentral()
}

apply from: "${rootProject.projectDir}/gradle/test.gradle"
apply from: "${rootProject.projectDir}/gradle/jacoco.gradle"

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.aspectj:aspectjweaver'
	
	implementation 'org.mapstruct:mapstruct:1.5.5.Final'
	
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.5.Final'
	annotationProcessor 'org.projectlombok:lombok-mapstruct-binding:0.2.0'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-test-autoconfigure'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	testImplementation 'org.assertj:assertj-core:3.24.2'
	testImplementation "org.wiremock:wiremock-jetty12:3.9.2"
	testImplementation 'org.testcontainers:junit-jupiter:1.20.1'
	testImplementation 'org.testcontainers:postgresql:1.20.1'
	testImplementation 'org.postgresql:postgresql:42.7.4'
	testAnnotationProcessor 'org.projectlombok:lombok:1.18.34'
	testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.6.2'
	testImplementation 'org.projectlombok:lombok:1.18.34'
}

tasks.named('test') {
	useJUnitPlatform()
}

spotless {
	java {
		target 'src/**/*.java'
		eclipse()
		removeUnusedImports()
		trimTrailingWhitespace()
		endWithNewline()
	}
}
